//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoTest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SoilTestEntities1 : DbContext
    {
        public SoilTestEntities1()
            : base("name=SoilTestEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_CollectionPoint> t_CollectionPoint { get; set; }
        public virtual DbSet<t_Sample> t_Sample { get; set; }
        public virtual DbSet<t_Task> t_Task { get; set; }
        public virtual DbSet<t_User> t_User { get; set; }
    }
}
