//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_CollectionPoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_CollectionPoint()
        {
            this.t_Task = new HashSet<t_Task>();
        }
    
        public string CollectionPointID { get; set; }
        public string District { get; set; }
        public string CountyLevel { get; set; }
        public string Altitude { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string GrainProduceCounty { get; set; }
        public string PointAddress { get; set; }
        public string PointPosition { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_Task> t_Task { get; set; }
    }
}
