//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Sample
    {
        public long SampleID { get; set; }
        public string TaskID { get; set; }
        public Nullable<System.DateTime> FinallyTime { get; set; }
        public string Text { get; set; }
        public string PictureURL { get; set; }
    
        public virtual t_Task t_Task { get; set; }
    }
}
