//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_Task()
        {
            this.t_Sample = new HashSet<t_Sample>();
        }
    
        public string TaskID { get; set; }
        public string UserID { get; set; }
        public int TaskState { get; set; }
        public string CollectionPointID { get; set; }
        public Nullable<System.DateTime> TimeRequest { get; set; }
        public string Reason { get; set; }
        public string SuperimposedLandSubtype { get; set; }
        public string SuperimposedLandType { get; set; }
        public string SuperimposedLandUse { get; set; }
        public string PictureURL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_Sample> t_Sample { get; set; }
        public virtual t_User t_User { get; set; }
        public virtual t_CollectionPoint t_CollectionPoint { get; set; }
    }
}
